# Generated by Django 5.2.3 on 2025-07-04 16:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        unique=True,
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="تحصیلات"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="شغل"
                    ),
                ),
                (
                    "mobile_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="استان"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شهر"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد پستی"
                    ),
                ),
                (
                    "full_address",
                    models.TextField(
                        blank=True, null=True, verbose_name="آدرس کامل پستی"
                    ),
                ),
                (
                    "purchase_credit",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0.0"),
                        max_digits=10,
                        verbose_name="اعتبار خرید",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
